Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\crm\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
Not Found: /static/drf-yasg/style.css
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui.css
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js
Not Found: /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js
Not Found: /static/drf-yasg/insQ.min.js
Not Found: /static/drf-yasg/url-polyfill.min.js
Not Found: /static/drf-yasg/swagger-ui-init.js
Not Found: /static/drf-yasg/immutable.min.js
Not Found: /static/drf-yasg/url-polyfill.min.js
Not Found: /static/drf-yasg/swagger-ui-init.js
Not Found: /static/drf-yasg/swagger-ui-dist/favicon-32x32.png
Not Found: /accounts/login/
Not Found: /accounts/login/
Not Found: /aapi
Not Found: /api
D:\F5 - Project\Django-CRM-master\crm\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
Watching for file changes with StatReloader
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /api
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
D:\F5 - Project\Django-CRM-master\crm\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Not Found: /
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Not Found: /
Not Found: /favicon.ico
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
D:\F5 - Project\Django-CRM-master\templates\registration changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: admin/base_site.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: admin/base_site.html
Not Found: /
Watching for file changes with StatReloader
Not Found: /api
Not Found: /api/
Unauthorized: /api/dashboard/
Not Found: /api/login
Method Not Allowed: /api/auth/login/
Unauthorized: /api/dashboard/
Not Found: /
Not Found: /api
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: admin/base_site.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: admin/base_site.html
D:\F5 - Project\Django-CRM-master\crm\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\crm\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\crm\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /accounts/login/
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /accounts/login/
Not Found: /accounts/login/
Not Found: /accounts/login/
Not Found: /accounts/login/
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: admin/base_site.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: admin/base_site.html
D:\F5 - Project\Django-CRM-master\templates\registration changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'admin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'admin' is not a registered namespace
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'admin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'admin' is not a registered namespace
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'admin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'admin' is not a registered namespace
D:\F5 - Project\Django-CRM-master\templates\adminka changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'adminka'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'adminka' is not a registered namespace
D:\F5 - Project\Django-CRM-master\templates\adminka changed, reloading.
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\templates\adminka changed, reloading.
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\templates\adminka changed, reloading.
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\templates\adminka changed, reloading.
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\templates\adminka changed, reloading.
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\templates\adminka changed, reloading.
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\templates\adminka changed, reloading.
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\templates\adminka changed, reloading.
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\templates\adminka changed, reloading.
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\templates\admin_base.html changed, reloading.
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\templates\login.html changed, reloading.
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\templates\admin_base.html changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: adminka/admin_base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: adminka/admin_base.html
D:\F5 - Project\Django-CRM-master\templates\registration changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: adminka/admin_base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: adminka/admin_base.html
D:\F5 - Project\Django-CRM-master\templates\assigned_to changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
D:\F5 - Project\Django-CRM-master\crm\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
D:\F5 - Project\Django-CRM-master\templates\registration changed, reloading.
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\templates\admin changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'admin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'admin' is not a registered namespace
D:\F5 - Project\Django-CRM-master\templates\admin changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'get_current_language'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 2: 'get_current_language'. Did you forget to register or load this tag?
D:\F5 - Project\Django-CRM-master\templates\admin changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'admin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'admin' is not a registered namespace
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: admin/base_site.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: admin/base_site.html
D:\F5 - Project\Django-CRM-master\templates\adminka changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: admin/base_site.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: admin/base_site.html
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: admin/base_site.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: admin/base_site.html
D:\F5 - Project\Django-CRM-master\templates\registration changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
D:\F5 - Project\Django-CRM-master\crm\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Watching for file changes with StatReloader
D:\F5 - Project\Django-CRM-master\crm\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Not Found: /
Watching for file changes with StatReloader
Not Found: /
Not Found: /
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
D:\F5 - Project\Django-CRM-master\crm\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "D:\F5 - Project\Django-CRM-master\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
D:\F5 - Project\Django-CRM-master\accounts\migrations\0012_remove_account_company.py changed, reloading.
